(() => {
  "use strict";
  const seen = () => { try { return localStorage.getItem("mueen_welcome_seen"); } catch { return "1"; } };
  if (!seen()) {
    const style = document.createElement("style");
    style.textContent = ".first-visit{position:fixed;inset:0;z-index:1200;display:grid;place-items:center;padding:20px;background:rgba(10,45,40,.46)}.first-visit-card{max-width:560px;padding:28px;border-radius:24px;background:var(--surface);color:var(--text);box-shadow:0 24px 70px rgba(0,0,0,.25);text-align:right}.first-visit-card h2{margin-top:0}";
    document.head.appendChild(style);
    const box=document.createElement("div"); box.className="first-visit";
    box.innerHTML='<section class="first-visit-card" role="dialog" aria-modal="true"><p class="eyebrow">مساحة المبرمج العربي</p><h2>مرحبًا بك في مُعين</h2><p>ابدأ بتنظيم مهامك وحفظ أكوادك وملاحظاتك من مكان واحد.</p><div class="item-actions"><button class="primary-button" id="firstVisitStart">ابدأ الآن</button><a class="small-action" href="welcome.html">صفحة التعريف الكاملة</a></div></section>';
    document.body.appendChild(box);
    box.querySelector("#firstVisitStart").onclick=()=>{try{localStorage.setItem("mueen_welcome_seen","1")}catch(_){} box.remove();};
  }
  const metricsKey = "mueen_usage_metrics_v1";
  function metric(name) { try { const x = JSON.parse(localStorage.getItem(metricsKey) || "{}"); x[name] = (x[name] || 0) + 1; localStorage.setItem(metricsKey, JSON.stringify(x)); } catch {} }
  document.addEventListener("click", e => { const page = e.target.closest("[data-page]")?.dataset.page; if (page) metric("page_" + page); });
  document.addEventListener("change", e => { if (e.target.matches("input[type=file]")) metric("file_import"); });
  document.addEventListener("dragover", e => { if (document.getElementById("editorPage")?.classList.contains("active-page")) e.preventDefault(); });
  document.addEventListener("drop", async e => {
    const editor = document.getElementById("editorPage");
    if (!editor?.classList.contains("active-page") || !e.dataTransfer?.files?.length) return;
    e.preventDefault();
    if (window.MUEEN_EDITOR?.import) { await window.MUEEN_EDITOR.import(e.dataTransfer.files); metric("drop_import"); if (window.toast) window.toast("تم استيراد الملفات المسقطة"); }
  });
  const clean = (v) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
  const modalBox = (title, body, bind) => { if (typeof window.modal === "function") { const box = window.modal(title, body, bind); return box; } return null; };
  function openPreviewTool() {
    const box=modalBox("معاينة HTML مباشرة", `<form><label>HTML وCSS<textarea name="html" rows="12" dir="ltr" placeholder="<h1>مرحبًا</h1><style>h1{color:teal}</style>"></textarea></label><div class="feature-card"><iframe id="quickPreviewFrame" title="معاينة HTML" sandbox="allow-scripts" style="width:100%;height:240px;border:1px solid var(--border);border-radius:12px;background:#fff"></iframe></div><div class="item-actions"><button class="primary-button">معاينة</button><button type="button" class="small-action" id="previewNewTab">فتح في نافذة جديدة</button></div></form>`, (f,root) => { const html=String(f.get("html")||""); root.querySelector("#quickPreviewFrame").srcdoc=html; root.querySelector("#previewNewTab").onclick=()=>{const w=window.open(); if(w){w.document.write(html);w.document.close();}}; });
    return box;
  }
  function toolModal(kind) {
    if (kind === "preview") return openPreviewTool();
    if (kind === "debug") return modalBox("مستكشف أخطاء الكود", `<form><label>اللغة<select name="lang"><option>JSON</option><option>JavaScript</option><option>HTML</option><option>CSS</option></select></label><label>الكود أو رسالة الخطأ<textarea name="code" rows="10" dir="ltr" placeholder="الصق الكود أو الخطأ هنا"></textarea></label><div id="debugResult" class="feature-card"></div><button class="primary-button">تحليل محلي</button></form>`, (f, box) => { const code=String(f.get("code")||""); const lang=String(f.get("lang")); const findings=[]; if(!code.trim()) findings.push("أدخل الكود أو رسالة الخطأ أولًا."); if(lang === "JSON") { try { JSON.parse(code); findings.push("JSON صالح ولا توجد أخطاء صياغة."); } catch(e) { findings.push("خطأ JSON: "+e.message+". راجع الفواصل وعلامات الاقتباس."); } } if(lang === "JavaScript" && /console\.log\s*\(/.test(code)) findings.push("تنبيه: توجد console.log؛ احذفها قبل النشر إن لم تكن ضرورية."); if(lang === "HTML" && /<img(?![^>]*alt=)/i.test(code)) findings.push("تنبيه وصول: صورة بلا alt."); if(lang === "CSS" && /!important/.test(code)) findings.push("تنبيه صيانة: قلّل استخدام !important."); box.querySelector("#debugResult").innerHTML=findings.map(x=>`<p>${clean(x)}</p>`).join(""); });
    if (kind === "api") return modalBox("مختبر API", `<form><label>الرابط<input name="url" type="url" dir="ltr" placeholder="https://api.example.com/data" required></label><label>الطريقة<select name="method"><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option></select></label><label>JSON Body<textarea name="body" rows="6" dir="ltr" placeholder='{"name":"Mueen"}'></textarea></label><div id="apiResult" class="feature-card"></div><button class="primary-button">إرسال الطلب</button></form>`, async (f, box) => { const url=String(f.get("url")); const method=String(f.get("method")); const raw=String(f.get("body")||""); const start=performance.now(); const result=box.querySelector("#apiResult"); try { const options={method,headers:{"Content-Type":"application/json"}}; if(method!=="GET"&&method!=="DELETE"&&raw.trim()){JSON.parse(raw);options.body=raw;} const res=await fetch(url,options); const text=await res.text(); result.innerHTML=`<p>الحالة: <strong>${res.status}</strong> · الزمن: ${Math.round(performance.now()-start)}ms</p><pre dir="ltr" style="white-space:pre-wrap;max-height:220px;overflow:auto">${clean(text.slice(0,10000))}</pre>`; } catch(e) { result.innerHTML=`<p>تعذر الطلب: ${clean(e.message)}. قد يمنع الخادم الطلب بسبب CORS.</p>`; } });
    if (kind === "builder") return modalBox("منشئ صفحة HTML", `<form><label>اسم الموقع<input name="name" value="موقعي"></label><label>الوصف<textarea name="desc" rows="3">صفحة عربية بسيطة وجميلة.</textarea></label><label>اللون الرئيسي<input name="color" type="color" value="#0f766e"></label><label>الأقسام<input name="sections" value="عن الموقع,الخدمات,تواصل معنا"></label><textarea name="out" rows="10" readonly dir="ltr"></textarea><div class="item-actions"><button class="primary-button">إنشاء</button><button type="button" class="small-action" id="builderCopy">نسخ HTML</button></div></form>`, (f, box) => { const name=clean(f.get("name")),desc=clean(f.get("desc")),color=f.get("color"),sections=String(f.get("sections")||"").split(",").map(x=>`<section><h2>${clean(x.trim())}</h2><p>${desc}</p></section>`).join(""); const out=`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${name}</title><style>body{font-family:Arial;margin:0;color:#17312d}header{padding:70px 8%;background:${color};color:white}main{max-width:900px;margin:auto;padding:20px}section{padding:30px 0;border-bottom:1px solid #ddd}</style></head><body><header><h1>${name}</h1><p>${desc}</p></header><main>${sections}</main></body></html>`; box.querySelector("[name=out]").value=out; box.querySelector("#builderCopy").onclick=()=>navigator.clipboard.writeText(out); });
    if (kind === "json-ts") return modalBox("JSON إلى TypeScript", `<form><label>JSON<textarea name="json" rows="10" dir="ltr" required></textarea></label><label>اسم الواجهة<input name="name" value="Root"></label><textarea name="out" rows="8" readonly dir="ltr"></textarea><button class="primary-button">تحويل</button></form>`, (f,box) => { try { const obj=JSON.parse(f.get("json")); const typeOf=v=>Array.isArray(v)?`${v.length&&typeof v[0]==="object"?"Array<"+typeOf(v[0])+">":"any[]"}`:v===null?"null":typeof v==="object"?"{\n"+Object.entries(v).map(([k,x])=>`  ${k}: ${typeOf(x)};`).join("\n")+"\n}":typeof v; const out=`export interface ${String(f.get("name")||"Root")} ${typeOf(obj)}`; box.querySelector("[name=out]").value=out; } catch(e) { box.querySelector("[name=out]").value="JSON غير صالح: "+e.message; } });
    if (kind === "image") return modalBox("مختبر الصور", `<form><label>اختر صورة<input name="file" type="file" accept="image/*"></label><label>الجودة<input name="quality" type="range" min="0.3" max="1" step="0.1" value="0.8"></label><div id="imageResult" class="feature-card"></div><button class="primary-button">تحليل وضغط</button></form>`, (f,box) => { const file=f.get("file"); const result=box.querySelector("#imageResult"); if(!file||!file.size) return result.textContent="اختر صورة أولًا."; const img=new Image(); img.onload=()=>{ const c=document.createElement("canvas"),scale=Math.min(1,1200/img.width); c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height); c.toBlob(blob=>{ const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mueen-optimized.webp";result.innerHTML=`<p>${file.name} · ${img.width}×${img.height} · ${Math.round(file.size/1024)}KB → ${Math.round(blob.size/1024)}KB</p><button type="button" class="small-action" id="imgDownload">تحميل WebP</button>`;result.querySelector("#imgDownload").onclick=()=>a.click(); },"image/webp",Number(f.get("quality"))); }; img.src=URL.createObjectURL(file); });
    if (kind === "regex") return modalBox("مولد Regex", `<form><label>النمط الجاهز<select name="preset"><option value="email">بريد إلكتروني</option><option value="phone">رقم هاتف</option><option value="url">رابط</option><option value="number">رقم</option></select></label><label>النص<textarea name="text" rows="5"></textarea></label><div id="regexResult" class="feature-card"></div><button class="primary-button">اختبار</button></form>`, (f,box) => { const patterns={email:"^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",phone:"^\\+?[0-9\\s-]{7,}$",url:"^https?:\\/\\/",number:"^-?\\d+(\\.\\d+)?$"}; const r=new RegExp(patterns[f.get("preset")],"m"); const hits=String(f.get("text")||"").split("\\n").filter(x=>r.test(x)); box.querySelector("#regexResult").innerHTML=`<code dir="ltr">${clean(patterns[f.get("preset")])}</code><p>المطابقات: ${hits.length}</p>`; });
    if (kind === "time-pro") return modalBox("الوقت المتقدم", `<form><label>التاريخ والوقت<input name="date" type="datetime-local"></label><label>التاريخ الثاني اختياري<input name="date2" type="datetime-local"></label><div id="timeResult" class="feature-card"></div><button class="primary-button">تحويل</button></form>`, (f,box) => { const d=new Date(f.get("date")); const d2=f.get("date2")?new Date(f.get("date2")):null; const r=box.querySelector("#timeResult"); r.innerHTML=`<p>ISO: <code dir="ltr">${d.toISOString()}</code></p><p>Unix: <code dir="ltr">${Math.floor(d.getTime()/1000)}</code></p>${d2?`<p>الفرق: ${Math.round(Math.abs(d2-d)/60000)} دقيقة</p>`:""}`; });
    if (kind === "site") return modalBox("فاحص الموقع السريع", `<form><label>رابط الموقع<input name="url" type="url" value="https://" required></label><div id="siteResult" class="feature-card"></div><button class="primary-button">فحص</button></form>`, async (f,box) => { const url=String(f.get("url")); const r=box.querySelector("#siteResult"); const base=url.replace(/\/$/,""); const checks=["/robots.txt","/sitemap.xml"]; try { const res=await fetch(url,{method:"GET"}); const html=await res.text(); const title=(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||"غير موجود"; r.innerHTML=`<p>الصفحة: ${res.ok?"تستجيب":"خطأ "+res.status}</p><p>العنوان: ${clean(title)}</p><p>HTTPS: ${url.startsWith("https://")?"نعم":"لا"}</p><p>${checks.map(x=>`<span>${x}: سيتم فحصه من نفس النطاق عند السماح بـ CORS</span>`).join("<br>")}</p>`; } catch(e){r.innerHTML=`<p>تعذر الفحص من المتصفح. قد يمنع الموقع الخارجي CORS.</p>`;} });
  }
  document.addEventListener("click", e => { const card=e.target.closest("[data-pro-tool]"); if(card){ e.preventDefault(); toolModal(card.dataset.proTool); } });

  window.MUEEN_USAGE = { read() { try { return JSON.parse(localStorage.getItem(metricsKey) || "{}"); } catch { return {}; } } };
})();